# Generated by Django 5.1.4 on 2026-04-06 19:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price_alter_orderitem_quantity'),
        ('site_support', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Inquiry',),
            ],
        ),
    ]