# Generated by Django 5.1.4 on 2025-11-21 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product Image')),
                ('name', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Product Name')),
                ('serial_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Serial Number')),
                ('description', models.TextField(verbose_name='Description')),
                ('size', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Size')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='Available Quantity')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmaterial')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product Image')),
                ('photo_name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Photo Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='products.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
