# Generated by Django 5.1.4 on 2025-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcolor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(blank=True, default='No Color', null=True),
        ),
    ]
