# Generated by Django 5.1.4 on 2025-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
