# Generated by Django 5.1.4 on 2026-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True),
        ),
    ]
