# Generated by Django 5.1.4 on 2026-02-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Available Quantity'),
        ),
    ]
