# Generated by Django 5.1.4 on 2026-03-10 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productmaterial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Photo Name'),
        ),
    ]
