# Generated by Django 5.1.4 on 2026-04-16 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options_alter_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bg',
            field=models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_bg',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_en',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='name_bg',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='name_en',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_bg',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
