# Generated by Django 5.1.4 on 2026-04-16 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_description_bg_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_bg',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Product Name'),
        ),
    ]
