# Generated by Django 5.1.4 on 2026-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
