# Generated by Django 5.1.4 on 2026-04-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
