"""
ElectryArt — Audit Event Names
Central registry of all structured audit events.

DO NOT rename existing events — they are part of the audit contract.
"""

# ======================
# CHECKOUT / ORDER FLOW
# ======================

CHECKOUT_STARTED = "CHECKOUT_STARTED"
CHECKOUT_EMPTY_CART = "CHECKOUT_EMPTY_CART"
CHECKOUT_VALIDATION_FAILED = "CHECKOUT_VALIDATION_FAILED"
ORDER_CREATE_STARTED = "ORDER_CREATE_STARTED"
ORDER_CREATED = "ORDER_CREATED"
CHECKOUT_COMPLETED_SIGNAL_QUEUED = "CHECKOUT_COMPLETED_SIGNAL_QUEUED"
ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED"

# Guest checkout

GUEST_CHECKOUT_STARTED = "GUEST_CHECKOUT_STARTED"
GUEST_CHECKOUT_EMPTY_CART = "GUEST_CHECKOUT_EMPTY_CART"
GUEST_CHECKOUT_VALIDATION_FAILED = "GUEST_CHECKOUT_VALIDATION_FAILED"
GUEST_ORDER_CREATE_STARTED = "GUEST_ORDER_CREATE_STARTED"
GUEST_ORDER_CREATED = "GUEST_ORDER_CREATED"
GUEST_CHECKOUT_COMPLETED_SIGNAL_QUEUED = "GUEST_CHECKOUT_COMPLETED_SIGNAL_QUEUED"
GUEST_ORDER_CREATE_FAILED = "GUEST_ORDER_CREATE_FAILED"

# ======================
# EMAIL
# ======================

ORDER_CONFIRMATION_EMAIL_ATTEMPT = "ORDER_CONFIRMATION_EMAIL_ATTEMPT"
ORDER_CONFIRMATION_EMAIL_SENT = "ORDER_CONFIRMATION_EMAIL_SENT"
ORDER_CONFIRMATION_EMAIL_FAILED = "ORDER_CONFIRMATION_EMAIL_FAILED"

# ======================
# ORDER STATUS
# ======================

ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"

# ======================
# AUTH / USER
# ======================

LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"
LOGOUT = "LOGOUT"
PROFILE_UPDATED = "PROFILE_UPDATED"

# ======================
# SYSTEM / SECURITY
# ======================

UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_ACCESS_ATTEMPT = "INVALID_ACCESS_ATTEMPT"
